### PR TITLE
[16.0][IMP] edi_oca: remove deprecated job functions

### PR DESCRIPTION
**Pull request by QuocDuong1306**
TODO from:
- https://github.com/OCA/edi-framework/commit/452b75b42ef3948fc2efaf02bc7ed296cef53408

### CODE REVIEW

**Comment by nilshamerlinck** [comment]
also need to impact tests:

image

**Comment by QuocDuong1306** [comment]
Hi @nilshamerlinck , because the jobs moved to `exchange records` instead of `backend`, do we need to take a chance to rename the `filename/classname` of `test_backend_jobs.py` to make it explicit

But if we change, may cause conflicts with the pending PRs

**Comment by nilshamerlinck** [comment]
yes indeed, please rename 
it's ok, this PR is some kind of low-priority "framework maintenance" PR

**Comment by QuocDuong1306** [comment]
Hi Nils, the PR is updated

**Review by nilshamerlinck — APPROVED** [review]
I think you can remove the `edi_oca/migrations/16.0.1.10.0/post-migrate.py` to avoid complaints from people that would have the module installed and would somehow rely on these old jobs

pre-approving

**Pull request closed without merging**
